# Generated by Django 3.2.8 on 2021-10-29 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=35)),
                ('sobrenome', models.CharField(max_length=35)),
                ('sexo', models.CharField(max_length=2)),
                ('altura', models.IntegerField()),
                ('peso', models.FloatField()),
                ('nascimento', models.DateField()),
                ('bairro', models.CharField(max_length=55)),
                ('cidade', models.CharField(max_length=55)),
                ('estado', models.CharField(max_length=55)),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='xsls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='xlsx')),
                ('uploaded', models.DateField(auto_now=True)),
                ('activated', models.BooleanField(default=False)),
            ],
        ),
    ]
