# Generated by Django 3.2.8 on 2021-10-29 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='sobrenome',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
